<?php $_nico_settings  = array (
  'options' => 
  array (
    '#language' => 
    array (
      'display' => 'block',
    ),
    '#currency' => 
    array (
      'display' => 'block',
    ),
    '#logo #text_under_logo' => 
    array (
      'display' => 'block',
    ),
    '#logo #image-logo' => 
    array (
      'display' => 'none',
    ),
    '#logo #text-logo' => 
    array (
      'display' => 'inline-block',
    ),
    '.product .actions button.btn' => 
    array (
      'display' => 'block',
    ),
  ),
  'settings' => 
  array (
    0 => NULL,
    'phone_number' => '07245465',
    'google_number' => 'google',
    'twitter' => 'http://twitter.com/NicoleThemes',
    'facebook' => 'http://www.facebook.com/pages/Nicole-Themes/201498429982413',
    'sale_text' => '-20%',
    'notification_hide_timeout' => '5000',
    'custom_css' => '',
    'first_visit_message' => '',
    'menu_search' => 'top',
    'menu_language' => 'left',
    'menu_currency' => 'left',
    'product_description' => 'bottom',
    'thumbs_location' => 'left',
    'pinterest' => '',
    'instagram' => '',
    'google' => 'http://www.gplus.com',
  ),
  'sliders' => 
  array (
    'Homepage' => 
    array (
      'active' => 'Camera slider',
    ),
    'Product page' => 
    array (
      'Cloud zoom' => 
      array (
        'showTitle' => 'false',
      ),
    ),
  ),
  'styles' => 
  array (
    'background_color' => '',
    'page_alignment' => '',
    'color' => 'color-red.css',
    'catalog_mode' => '',
  ),
  'background-image' => 'none',
);