<?php
global $nico_theme_name, $nico_theme, $nico_theme_positions;
$nico_theme_name = '<div style="color:#333;float:right;opacity:0.5;font-weight:600;"><span style="color:#3333">xez</span><span style="color:#0080c8">pro</span></div>';
$nico_theme = 'xezpro';
$nico_theme_positions = 
array(
	'menu' => 'Menu',
	'top' => 'Page top',
	'top_links' => 'Top links',
	'header' => 'Header',
	'above_footer' => 'Above footer',
	'footer_top' => 'Footer top',
	'footer_bottom' => 'Footer bottom',
	'footer_column' => 'Footer column',
	'content_top' => 'Content top',
	'content_bottom' => 'Content bottom',
	'column_left' => 'Column left',
	'column_right' => 'Column right',
	'product_tabs' => 'Product tabs (product page)'
);

$nico_import_stores = 
array(
	'xezpro.nicolette.ro' => 'xezpro',
);

$ocmods_ignore = array('nico_image_cropresize.ocmod.xml', 'nico_image_resizewidth.ocmod.xml', 'nico_image_cropresize_category.ocmod.xml', 'nico_image_cropresize_product.ocmod.xml', 'nico_image_resizewidth.ocmod.xml', 'nico_image_resizewidth_category.ocmod.xml', 'nico_image_resizewidth_product.ocmod.xml');
